USE sakila;


-- 1. Total Revenue and Reporting Period Write an SQL query to calculate the total revenue generated by each store, including:• Store ID • Total revenue • Earliest payment date • Latest payment date Use the payment table and connect payments to stores through the appropriate relationships.*/
 
 SELECT 
    c.store_id AS StoreID,
    SUM(p.amount) AS TotalRevenue,
    MIN(p.payment_date) AS EarliestPaymentDate,
    MAX(p.payment_date) AS LatestPaymentDate
FROM payment p
JOIN customer c 
ON p.customer_id = c.customer_id
GROUP BY c.store_id
ORDER BY c.store_id;

-- 2. Write a SQL query to show the monthly revenue breakdown for each store, including: • Store ID  • Revenue month  • Total monthly revenue  Sort the results by store and month. 

SELECT 
    c.store_id AS StoreID,
    DATE_FORMAT(p.payment_date, '%Y-%m') AS RevenueMonth,
    SUM(p.amount) AS TotalMonthlyRevenue
FROM payment p
JOIN customer c 
ON p.customer_id = c.customer_id
GROUP BY 
    c.store_id,
    DATE_FORMAT(p.payment_date, '%Y-%m')
ORDER BY 
    c.store_id,
    RevenueMonth;
    
    -- 3. Write a SQL query that compares each store’s total revenue to the company total, showing: • Store ID  • Store revenue  • Total company revenue  • Percentage of total revenue contributed by each store  
    
SELECT 
    c.store_id,
    SUM(p.amount) AS store_revenue,
    (SELECT SUM(amount) FROM payment) AS company_total_revenue,
    (SUM(p.amount) / (SELECT SUM(amount) FROM payment)) * 100 AS percent_of_total
FROM payment p
JOIN customer c
    ON p.customer_id = c.customer_id
GROUP BY c.store_id
ORDER BY c.store_id;

-- 4. Write a SQL query to determine the number of rentals per month and the average payment amount per rental category. Return: • Rental month  • Category name  • Number of rentals  • Average payment amount  

SELECT 
    DATE_FORMAT(r.rental_date, '%Y-%m') AS rental_month,
    c.name AS category_name,
    COUNT(r.rental_id) AS number_of_rentals,
    AVG(p.amount) AS average_payment_amount
FROM rental r
JOIN payment p
    ON r.rental_id = p.rental_id
JOIN inventory i
    ON r.inventory_id = i.inventory_id
JOIN film f
    ON i.film_id = f.film_id
JOIN film_category fc
    ON f.film_id = fc.film_id
JOIN category c
    ON fc.category_id = c.category_id
GROUP BY rental_month, c.name
ORDER BY rental_month, c.name;

-- 5. 5. Store Performance Ranking 

SELECT 
    s.store_id,
    SUM(p.amount) AS total_revenue,
    COUNT(r.rental_id) AS total_rentals,
    ROUND(AVG(p.amount), 2) AS avg_payment,
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS revenue_rank
FROM store s
JOIN staff st ON s.store_id = st.store_id
JOIN payment p ON st.staff_id = p.staff_id
JOIN rental r ON p.rental_id = r.rental_id
GROUP BY s.store_id;

