# Data Analytics — Exercise 7.2: Pandas Essentials
## Patrick Green-Holloway | Date: 2026-05-21

This notebook uses Pandas to create, inspect, filter, and summarize employee sales data for RetailHub Inc. It practices DataFrame creation, Boolean filtering, calculated columns, lambda functions, and GroupBy aggregation.

## 1. Import Pandas and Create the DataFrame
We import Pandas using the standard `pd` alias and build a DataFrame from a Python dictionary of employee sales records.

In [1]:
# import Pandas and create the DataFrame
import pandas as pd

# Employee sales data: 8 records and 4 columns
data = {
    'name': ['Alice', 'Ben', 'Carmen', 'Dev', 'Eve', 'Frank', 'Grace', 'Hiro'],
    'city': ['London', 'Manchester', 'London', 'Leeds',
             'Birmingham', 'Manchester', 'Leeds', 'London'],
    'sales': [4200.0, 3100.0, 5050.0, 2800.0,
              1950.0, 3750.0, 4600.0, 3300.0],
    'months': [12, 6, 24, 3, 18, 9, 15, 7]
}

df = pd.DataFrame(data)

print('── Employee DataFrame ──────────────────────')
print(df)
print(f"\nShape: {df.shape}")
print("\nData types:")
print(df.dtypes)
print("\ndf.info():")
df.info()


── Employee DataFrame ──────────────────────
     name        city   sales  months
0   Alice      London  4200.0      12
1     Ben  Manchester  3100.0       6
2  Carmen      London  5050.0      24
3     Dev       Leeds  2800.0       3
4     Eve  Birmingham  1950.0      18
5   Frank  Manchester  3750.0       9
6   Grace       Leeds  4600.0      15
7    Hiro      London  3300.0       7

Shape: (8, 4)

Data types:
name          str
city          str
sales     float64
months      int64
dtype: object

df.info():
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    8 non-null      str    
 1   city    8 non-null      str    
 2   sales   8 non-null      float64
 3   months  8 non-null      int64  
dtypes: float64(1), int64(1), str(2)
memory usage: 388.0 bytes


## 2. Inspect and Describe the Data
We preview the first and last rows, then use summary statistics to understand the numeric columns.

In [2]:
# inspect and describe the data
print('First 3 rows:')
print(df.head(3))

print('Last 3 rows:')
print(df.tail(3))

print('Summary statistics:')
print(df.describe())

print(f'Mean sales: £{df["sales"].mean():,.2f}')
print(f'Max sales: £{df["sales"].max():,.2f}')

First 3 rows:
     name        city   sales  months
0   Alice      London  4200.0      12
1     Ben  Manchester  3100.0       6
2  Carmen      London  5050.0      24
Last 3 rows:
    name        city   sales  months
5  Frank  Manchester  3750.0       9
6  Grace       Leeds  4600.0      15
7   Hiro      London  3300.0       7
Summary statistics:
             sales     months
count     8.000000   8.000000
mean   3593.750000  11.750000
std    1013.282326   6.964194
min    1950.000000   3.000000
25%    3025.000000   6.750000
50%    3525.000000  10.500000
75%    4300.000000  15.750000
max    5050.000000  24.000000
Mean sales: £3,593.75
Max sales: £5,050.00


## 3. Select, Filter, and Sort
We select specific columns, filter employees above a sales amount, sort the data, and display the top seller.

In [3]:
# select, filter, and sort
name_sales = df[['name', 'sales']]
print('Name and Sales columns:')
print(name_sales)

high_sales = df[df['sales'] > 3500.0]
print('Employees with sales above £3,500:')
print(high_sales)

df_sorted = df.sort_values('sales', ascending=False).reset_index(drop=True)
print('Full DataFrame sorted by sales, highest first:')
print(df_sorted)

print('Top-selling employee full record:')
print(df_sorted.iloc[0])

Name and Sales columns:
     name   sales
0   Alice  4200.0
1     Ben  3100.0
2  Carmen  5050.0
3     Dev  2800.0
4     Eve  1950.0
5   Frank  3750.0
6   Grace  4600.0
7    Hiro  3300.0
Employees with sales above £3,500:
     name        city   sales  months
0   Alice      London  4200.0      12
2  Carmen      London  5050.0      24
5   Frank  Manchester  3750.0       9
6   Grace       Leeds  4600.0      15
Full DataFrame sorted by sales, highest first:
     name        city   sales  months
0  Carmen      London  5050.0      24
1   Grace       Leeds  4600.0      15
2   Alice      London  4200.0      12
3   Frank  Manchester  3750.0       9
4    Hiro      London  3300.0       7
5     Ben  Manchester  3100.0       6
6     Dev       Leeds  2800.0       3
7     Eve  Birmingham  1950.0      18
Top-selling employee full record:
name      Carmen
city      London
sales     5050.0
months        24
Name: 0, dtype: object


## 4. Add a Calculated Column and Conditional Rating
We calculate each employee's 8% commission and add a performance rating based on their sales amount.

In [4]:
# add commission and rating columns

df['commission'] = df['sales'] * 0.08

df['rating'] = df['sales'].apply(
    lambda sale: 'Star' if sale >= 4000 else ('Good' if sale >= 2500 else 'Developing')
)

print('Updated DataFrame with commission and rating:')
print(df)

print('── Commission per Employee ──────────────')
for _, row in df.iterrows():
    print(f'{row["name"]:<8} | £{row["commission"]:>8,.2f} | {row["rating"]}')


Updated DataFrame with commission and rating:
     name        city   sales  months  commission      rating
0   Alice      London  4200.0      12       336.0        Star
1     Ben  Manchester  3100.0       6       248.0        Good
2  Carmen      London  5050.0      24       404.0        Star
3     Dev       Leeds  2800.0       3       224.0        Good
4     Eve  Birmingham  1950.0      18       156.0  Developing
5   Frank  Manchester  3750.0       9       300.0        Good
6   Grace       Leeds  4600.0      15       368.0        Star
7    Hiro      London  3300.0       7       264.0        Good
── Commission per Employee ──────────────
Alice    | £  336.00 | Star
Ben      | £  248.00 | Good
Carmen   | £  404.00 | Star
Dev      | £  224.00 | Good
Eve      | £  156.00 | Developing
Frank    | £  300.00 | Good
Grace    | £  368.00 | Star
Hiro     | £  264.00 | Good


## 5. GroupBy — Aggregate Statistics by City
We group the employees by city to compare total sales, average sales, and employee counts by location.

In [5]:
# GroupBy aggregate statistics by city

city_totals = df.groupby('city')['sales'].sum()
print('── Total Sales by City ──────────────────')
print(city_totals)

city_means = df.groupby('city')['sales'].mean()
print('── Mean Sales by City ───────────────────')
print(city_means)

city_summary = df.groupby('city').agg({'sales': ['sum', 'mean', 'count']})
print('── Full City Summary ────────────────────')
print(city_summary)

top_city = city_totals.idxmax()
print(f'Top city: {top_city} Total: £{city_totals[top_city]:,.2f}')


── Total Sales by City ──────────────────
city
Birmingham     1950.0
Leeds          7400.0
London        12550.0
Manchester     6850.0
Name: sales, dtype: float64
── Mean Sales by City ───────────────────
city
Birmingham    1950.000000
Leeds         3700.000000
London        4183.333333
Manchester    3425.000000
Name: sales, dtype: float64
── Full City Summary ────────────────────
              sales                   
                sum         mean count
city                                  
Birmingham   1950.0  1950.000000     1
Leeds        7400.0  3700.000000     2
London      12550.0  4183.333333     3
Manchester   6850.0  3425.000000     2
Top city: London Total: £12,550.00


## Summary
London is the top-performing city with total sales of **£12,550.00** from 3 employees. The strongest individual performer is **Carmen**, who made **£5,050.00** in sales and earned a **Star** rating. Based on the GroupBy results, RetailHub should continue investing in London while looking for ways to improve Birmingham because it has the lowest total sales.

## Extension Challenge 1 — Sales Bands
This extra cell groups sales into three equal-width bands and counts how many employees fall into each band.

In [6]:
sales_bands = df['sales'].value_counts(bins=3)

print('Sales grouped into 3 bands:')
print(sales_bands)

Sales grouped into 3 bands:
(2983.333, 4016.667]              3
(4016.667, 5050.0]                3
(1946.8990000000001, 2983.333]    2
Name: count, dtype: int64


## Extension Challenge 2 — Pivot Table
This extra cell creates a pivot table showing average sales by city and compares it to the GroupBy mean result.

In [7]:
pivot_sales = pd.pivot_table(df, values='sales', index='city', aggfunc='mean')

print('Pivot table — average sales by city:')
print(pivot_sales)

print('\nGroupBy mean — average sales by city:')
print(city_means)


Pivot table — average sales by city:
                  sales
city                   
Birmingham  1950.000000
Leeds       3700.000000
London      4183.333333
Manchester  3425.000000

GroupBy mean — average sales by city:
city
Birmingham    1950.000000
Leeds         3700.000000
London        4183.333333
Manchester    3425.000000
Name: sales, dtype: float64


## Extension Challenge 3 — Rank by Tenure
This extra cell sorts employees by months with the company and adds a rank column.

In [8]:
tenure_rank = df.sort_values('months').reset_index(drop=True)
tenure_rank['rank'] = tenure_rank.index + 1

print('Employees ranked by tenure:')
print(tenure_rank)

Employees ranked by tenure:
     name        city   sales  months  commission      rating  rank
0     Dev       Leeds  2800.0       3       224.0        Good     1
1     Ben  Manchester  3100.0       6       248.0        Good     2
2    Hiro      London  3300.0       7       264.0        Good     3
3   Frank  Manchester  3750.0       9       300.0        Good     4
4   Alice      London  4200.0      12       336.0        Star     5
5   Grace       Leeds  4600.0      15       368.0        Star     6
6     Eve  Birmingham  1950.0      18       156.0  Developing     7
7  Carmen      London  5050.0      24       404.0        Star     8


## Extension Challenge 4 — Star Performers
This extra cell filters only Star performers and calculates their combined commission.

In [9]:
star_performers = df[df['rating'] == 'Star'][['name', 'city', 'sales', 'commission']]
combined_star_commission = star_performers['commission'].sum()

print('Star performers:')
print(star_performers)
print(f'Combined Star performer commission: £{combined_star_commission:,.2f}')


Star performers:
     name    city   sales  commission
0   Alice  London  4200.0       336.0
2  Carmen  London  5050.0       404.0
6   Grace   Leeds  4600.0       368.0
Combined Star performer commission: £1,108.00


## Extension Challenge 5 — Missing Data Practice
This extra cell simulates a missing sales value, detects it, fills it with the mean, and prints the cleaned DataFrame.

In [10]:
missing_df = df.copy()
missing_df.loc[2, 'sales'] = None

print('Missing values before cleaning:')
print(missing_df.isnull().sum())

missing_df['sales'] = missing_df['sales'].fillna(missing_df['sales'].mean())

print('Missing values after cleaning:')
print(missing_df.isnull().sum())

print('Cleaned DataFrame:')
print(missing_df)


Missing values before cleaning:
name          0
city          0
sales         1
months        0
commission    0
rating        0
dtype: int64
Missing values after cleaning:
name          0
city          0
sales         0
months        0
commission    0
rating        0
dtype: int64
Cleaned DataFrame:
     name        city        sales  months  commission      rating
0   Alice      London  4200.000000      12       336.0        Star
1     Ben  Manchester  3100.000000       6       248.0        Good
2  Carmen      London  3385.714286      24       404.0        Star
3     Dev       Leeds  2800.000000       3       224.0        Good
4     Eve  Birmingham  1950.000000      18       156.0  Developing
5   Frank  Manchester  3750.000000       9       300.0        Good
6   Grace       Leeds  4600.000000      15       368.0        Star
7    Hiro      London  3300.000000       7       264.0        Good


## Extension Challenge 6 — Export and Re-read CSV
This extra cell exports the final DataFrame to a CSV file, re-reads it, and checks that the shape matches.

In [11]:
df.to_csv('employee_sales.csv', index=False)

reloaded_df = pd.read_csv('employee_sales.csv')

print('Original shape:', df.shape)
print('Reloaded shape:', reloaded_df.shape)
print('Shapes match:', df.shape == reloaded_df.shape)

Original shape: (8, 6)
Reloaded shape: (8, 6)
Shapes match: True
